sous-chefs/sc-mongodb

README.md

PR to test travis-ci webhook and run a first test.

Add fork note to License

---

.rubocop.yml
.travis.yml
Gemfile

Source: https://github.com/edelight/chef-mongodb/pull/382

Use Travis CI container infra and caching for faster builds

---

attributes/default.rb
recipes/user_management.rb

Source: https://github.com/edelight/chef-mongodb/pull/384

use mongo gem version 1.X

---

templates/default/redhat-mongodb.init.erb

Source: https://github.com/edelight/chef-mongodb/pull/363

Moved the ulimit commands to the start function

---

README.md
attributes/default.rb
recipes/install.rb

Source: https://github.com/edelight/chef-mongodb/pull/367

Add a new install method 'none' that doesn't install.

---

definitions/mongodb.rb
recipes/install.rb

Source: https://github.com/edelight/chef-mongodb/pull/373

Cookbook doesn't work on Amazon Linux

---

templates/default/debian-mongodb.upstart.erb

Source: https://github.com/edelight/chef-mongodb/pull/360

Add NUMA support to debian-mongodb upstart script

---

definitions/mongodb.rb

Source: https://github.com/edelight/chef-mongodb/pull/368

fix for bug #348 - broken sharding

---

libraries/mongodb.rb

Source: https://github.com/edelight/chef-mongodb/pull/356

Adds ability to use ipaddress instead of fqdn in replicaset

---

.kitchen.yml
Berksfile
test/integration/nodes/mongodb-replica-001.json

Source: https://github.com/edelight/chef-mongodb/pull/314

replica: include example replica member node

---

providers/user.rb

Source: https://github.com/edelight/chef-mongodb/pull/359

fix creating user bug for custom host and port

---

templates/default/debian-mongodb.upstart.erb

This pull request is to fix issue #89

Changed order of operations in init, so that context set before NUMA mods.

---

test/unit/default_spec.rb
test/unit/install_spec.rb

This parenthesizes arguments to avoid DLTK/Lint warnings

Fix a plethora of parenthesize arguments warnings

---

libraries/mongodb.rb

I encountered this problem of having _id > 255 where mongodb considers it as invalid _id. The current recipe will get max_id += 1, which leads _id to grows to the top value.
The validation logic is here:
https://github.com/mongodb/mongo/blob/r3.2.0/src/mongo/db/repl/member_config.cpp#L225
To fix the problem, instead of using max_id +=1, we pick a value between [0,255] for _id, excluding the _id's have existed in the member configs.
This patch is copied from:
https://github.com/edelight/chef-mongodb/pull/410#issuecomment-168934264

bug fix in member_config for having _id > 255

---

README.md
attributes/users.rb
libraries/mongodb.rb
providers/user.rb
recipes/user_management.rb

Source: https://github.com/edelight/chef-mongodb/pull/344

User management in replicasets / sharding

---

libraries/mongodb.rb

Source: https://github.com/edelight/chef-mongodb/pull/380

Force rs.reconfig when there are no old members

---

attributes/default.rb
recipes/install.rb

Source: https://github.com/edelight/chef-mongodb/pull/377

Packager Options Attribute

---

CHANGELOG.md
metadata.rb

Only encompasses cookbook name change

Bump to 0.18.0 to tag release

---

attributes/default.rb

otherwise the cookbook will fail due to the renaming of the cookbook

Fixes cookbook name in attributes

---

recipes/replicaset.rb
recipes/shard.rb
test/unit/default_spec.rb
test/unit/install_spec.rb
test/unit/mms_backup_agent_spec.rb
test/unit/mms_monitoring_agent_spec.rb

node.set will be removed in Chef 14:
https://docs.chef.io/deprecations_attributes.html#set-and-set-unless

node.set has been deprecated in favor of using explicit precedence level

---

metadata.rb
recipes/mongodb_org_repo.rb
resources/user.rb

Rake returns an exit status of 1 after running Foodcritic in Travis. This PR resolves the issues reported by Foodcritic so Travis should start passing the build.

Fix FC024, FC069, FC074, FC078

---

.kitchen.yml
TESTING.md
definitions/mongodb.rb
libraries/mongodb.rb
recipes/replicaset.rb
recipes/shard.rb
test/fixtures/cookbooks/mongodb_spec/recipes/set_hostname.rb
test/integration/nodes/mongo1.json
test/integration/nodes/mongo2.json
test/integration/nodes/mongo3.json
test/integration/nodes/shard1-n1.json
test/integration/nodes/shard1-n2.json
test/integration/nodes/shard1-n3.json
test/integration/replicaset3/inspec/replicaset_spec.rb
test/integration/shard-mongos/inspec/shard_spec.rb

Updates/fixes replicaset and shard config + testing

Rewrite part4

---

definitions/mongodb.rb
libraries/mongodb.rb

Rebase of https://github.com/sous-chefs/mongodb/pull/8 on the `rewrite_v1` branch

Rewrite part5

---

.kitchen.dokken.yml
.kitchen.yml
.travis.yml
README.md
attributes/mms_agent.rb
recipes/mms_automation_agent.rb
recipes/mms_backup_agent.rb
recipes/mms_monitoring_agent.rb
resources/agent.rb
test/integration/mms_agent/inspec/automation_agent_spec.rb
test/integration/mms_agent/inspec/backup_agent_spec.rb
test/integration/mms_agent/inspec/monitoring_agent_spec.rb
test/integration/mms_backup_agent/inspec/backup_agent_spec.rb

Closes https://github.com/sous-chefs/mongodb/issues/67
Closes https://github.com/sous-chefs/mongodb/issues/68

Add mongodb_agent resource and update mms recipes

---

.kitchen.yml
.travis.yml
libraries/mongodb.rb
spec/recipes/default_spec.rb
test/integration/replicaset3/inspec/replicaset_spec.rb
test/integration/shard-mongos/inspec/shard_spec.rb

This is related to #165, it's a simple refactor to ease understanding of the code to be changed in the other issue.
My argument is that the replicaset member configuration should be constant for every run, with the same set of attributes.
This will make it easier to make sense of the replicaset code

Extract replicaset member creation logic

---

libraries/mongodb.rb

This attempt is to use same variables names throughout the script, and also to reduce the code on not needed parts.

Refactor replicaset update

---

CHANGELOG.md
definitions/mongodb.rb
metadata.rb
resources/agent.rb
spec/recipes/default_spec.rb

Documentation and version bump for version 1.0.1

Prepare for publishing 1.0.1

---

recipes/install.rb

Fix Invalid Keyfile Option

---

CHANGELOG.md
README.md
recipes/install.rb

Fix packages version pin for Debian, more info in #220 issue.
Fixes #220, #221 
P.S. Also it would be nice to update cookbook in the Supermarket. There is only the 1.2.0 version.

Fix packages version pin for Debian, fix CI badge

---

attributes/default.rb
definitions/mongodb.rb
libraries/mongodb.rb
recipes/configserver.rb
recipes/default.rb
recipes/install.rb
recipes/mms_automation_agent.rb
recipes/mms_backup_agent.rb
recipes/mms_monitoring_agent.rb
recipes/mongo_gem.rb
recipes/mongodb_org_repo.rb
recipes/mongos.rb
recipes/replicaset.rb
recipes/shard.rb
recipes/user_management.rb
resources/agent.rb

Auto-corrected with Cookstyle
Signed-off-by: Tim Smith <tsmith@chef.io>

Use chef-style comment header & modes as strings

---

CHANGELOG.md
README.md
attributes/dbconfig.rb
attributes/default.rb
attributes/mms_agent.rb
definitions/mongodb.rb
metadata.rb
recipes/install.rb
recipes/mms_backup_agent.rb
recipes/mms_monitoring_agent.rb
recipes/mongodb_org_repo.rb
spec/recipes/default_spec.rb
spec/spec_helper.rb
test/fixtures/cookbooks/mongodb_spec/recipes/set_hostname.rb
test/unit/default_spec.rb
test/unit/install_spec.rb
test/unit/mms_backup_agent_spec.rb
test/unit/mms_monitoring_agent_spec.rb

Fix some cookstyle warnings in this cookbook.

More Cookstyle fixes

---

CHANGELOG.md
metadata.rb

release 3.0.0

---

CHANGELOG.md
metadata.rb
resources/agent.rb
resources/user.rb

Hey!
I ran Cookstyle 7.26.1 against this repo and here are the results.
This repo was selected due to the topics of chef-cookbook
- 1:1 refactor: `Chef/Deprecations/ResourceWithoutUnifiedTrue` - Set `unified_mode true` in Chef Infra Client 15.3+ custom resources to ensure they work correctly in Chef Infra Client 18 (April 2022) when Unified Mode becomes the default. (https://docs.chef.io/workstation/cookstyle/chef_deprecations_resourcewithoutunifiedtrue)
- 1:1 refactor: `Chef/Deprecations/ResourceWithoutUnifiedTrue` - Set `unified_mode true` in Chef Infra Client 15.3+ custom resources to ensure they work correctly in Chef Infra Client 18 (April 2022) when Unified Mode becomes the default. (https://docs.chef.io/workstation/cookstyle/chef_deprecations_resourcewithoutunifiedtrue)

Automated PR: Cookstyle Changes

---

CHANGELOG.md

Describe what this change achieves
List any existing issues this PR resolves

Fix markdown

---

.github/workflows/ci.yml
CHANGELOG.md

Describe what this change achieves
List any existing issues this PR resolves

Update tested platforms
